// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB4i-fjVPdjwg5wrhrT94aC_G6kNKsFN28',
    appId: '1:109977431110:web:abbe15375a88a443e66e47',
    messagingSenderId: '109977431110',
    projectId: 'car-detector-833e5',
    authDomain: 'car-detector-833e5.firebaseapp.com',
    storageBucket: 'car-detector-833e5.firebasestorage.app',
    measurementId: 'G-M9QFDP2LBM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBHDbvlEgWDQ4aS8VlDcGBr14-IL6_bLkg',
    appId: '1:109977431110:android:85de0a8bf0bedc89e66e47',
    messagingSenderId: '109977431110',
    projectId: 'car-detector-833e5',
    storageBucket: 'car-detector-833e5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAFYnQT-QTycT6ku_zDZ6Db18HhTuqeEEU',
    appId: '1:109977431110:ios:fd0dfa530fd2e02ee66e47',
    messagingSenderId: '109977431110',
    projectId: 'car-detector-833e5',
    storageBucket: 'car-detector-833e5.firebasestorage.app',
    iosBundleId: 'com.example.carDetector',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAFYnQT-QTycT6ku_zDZ6Db18HhTuqeEEU',
    appId: '1:109977431110:ios:fd0dfa530fd2e02ee66e47',
    messagingSenderId: '109977431110',
    projectId: 'car-detector-833e5',
    storageBucket: 'car-detector-833e5.firebasestorage.app',
    iosBundleId: 'com.example.carDetector',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB4i-fjVPdjwg5wrhrT94aC_G6kNKsFN28',
    appId: '1:109977431110:web:fd426c716474a1a4e66e47',
    messagingSenderId: '109977431110',
    projectId: 'car-detector-833e5',
    authDomain: 'car-detector-833e5.firebaseapp.com',
    storageBucket: 'car-detector-833e5.firebasestorage.app',
    measurementId: 'G-S78DMPT9S3',
  );
}
