name: car_detector_api
description: Car Detector REST API for Cloud Run
version: 1.0.0
publish_to: none

environment:
  sdk: ^3.3.0

dependencies:
  shelf: ^1.4.1
  shelf_router: ^1.1.4
  google_generative_ai: ^0.4.3
  http: ^1.2.1
  image: ^4.1.4
  mime: ^1.0.4
  crypto: ^3.0.3
